[package]
name = "gpapi"
version = "0.4.0"
authors = ["David Weinstein <dweinst@insitusec.com>", "Bill Budington <bill@eff.org>"]
build = "build.rs"
license = "MIT"
edition = "2018"
description = "A library for interacting with the Google Play API"
homepage = "https://github.com/EFForg/rs-google-play/tree/master/gpapi"
repository = "https://github.com/EFForg/rs-google-play/tree/master/gpapi"

[dependencies]
protobuf = { version = "2", features = ["with-bytes", "with-serde"] }
reqwest = { version = "0.11", features = ["stream"] }
bytes = "1"
openssl = "0.10"
base64 = "0.13"
byteorder = "1"
hex = "0.4"
lazy_static = "1.4"
hyper = { version = "0.14", features = ["full"] }
hyper-openssl = "0.9"
googleplay-protobuf = { version = "0.1", features = ["with-serde"] }
bincode = "1"
futures-util = { version = "0.3", features = ["io"] }
tokio-dl-stream-to-disk = "0.2"

[build-dependencies]
googleplay-protobuf = { version = "0.1", features = ["with-serde"] }
protobuf = { version = "2", features = ["with-bytes", "with-serde"] }
bincode = "1"
configparser = "3"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
